version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: docker-next
    command: pnpm run dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
