---
name: Deploy to staging
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Run-tests-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Build Docker image
        run: docker build -t unit-test --target test .

      - name: Run tests in Docker container
        run: docker run --rm --name run-ut unit-test

      - name: Setup Node.js environment
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install pnpm for deployment
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: npm install -g pnpm

      - name: Install Vercel CLI
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
