---
name: Deploy to production
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Deploy-to-Vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t portfolio-prod:latest --quiet --compress --target production .
          docker tag portfolio-prod:latest "${DOCKERHUB_USERNAME}/portfolio-prod:latest"
          docker push "${DOCKERHUB_USERNAME}/portfolio-prod:latest"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token="${VERCEL_TOKEN}"

      - name: Build Project Artifacts
        run: vercel build --prod --token="${VERCEL_TOKEN}"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token="${VERCEL_TOKEN}"
