---
name: Deploy to staging
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Build Docker image
        run: docker build -t unit-test --target test .

      - name: Run tests in Docker container
        run: docker run --rm --name run-ut unit-test

  Deploy-to-staging:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: Run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install pnpm for deployment
        run: npm install -g pnpm

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="${VERCEL_TOKEN}"

      - name: Build Project Artifacts
        run: vercel build --token="${VERCEL_TOKEN}"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="${VERCEL_TOKEN}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t portfolio-dev:latest --quiet --compress --target development .
          docker tag portfolio-dev:latest "${DOCKERHUB_USERNAME}/portfolio-dev:latest"
          docker push "${DOCKERHUB_USERNAME}/portfolio-dev:latest"