---
name: Deploy to staging
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Build Docker image
        run: docker build --no-cache -t unit-test --target test .

      - name: Run tests in Docker container
        run: docker run --rm --name run-ut unit-test

      - name: Login to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker build -t portfolio-dev:latest --quiet --compress --target dev .
          docker tag portfolio-dev:latest "${DOCKERHUB_USERNAME}/portfolio-dev:latest"
          docker push "${DOCKERHUB_USERNAME}/portfolio-dev:latest"

  Deploy-to-staging:
    runs-on: ubuntu-latest
    needs: Run-tests
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Install pnpm for deployment
        run: npm install -g pnpm

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="${VERCEL_TOKEN}"

      - name: Build Project Artifacts
        run: vercel build --token="${VERCEL_TOKEN}"

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="${VERCEL_TOKEN}"
